micronaut:
    application:
        name: reactive
    router:
        static:
            resources:
                enabled: true
                mapping: /static/**
                paths: classpath:static
    server:
        port: 47977
